version: "3"
services:
  node:
    build:
     context: .
     dockerfile: docker/dockerfile-node
    volumes:
       - ./:/code
    working_dir: /code
    command: npm run dev
    environment:
      HOST: 0.0.0.0
      API: 'http://localhost:8080/v1/'
    ports:
      - "3000:3000"
